#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'core_sys' in
 * file 'core_sys.swinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following masters:
 *   h2f_axi_master
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'from_hps', class 'altera_avalon_pio'
 * The macros are prefixed with 'FROM_HPS_'.
 * The prefix is the slave descriptor.
 */
#define FROM_HPS_COMPONENT_TYPE altera_avalon_pio
#define FROM_HPS_COMPONENT_NAME from_hps
#define FROM_HPS_BASE 0x0
#define FROM_HPS_SPAN 16
#define FROM_HPS_END 0xf
#define FROM_HPS_BIT_CLEARING_EDGE_REGISTER 0
#define FROM_HPS_BIT_MODIFYING_OUTPUT_REGISTER 0
#define FROM_HPS_CAPTURE 0
#define FROM_HPS_DATA_WIDTH 32
#define FROM_HPS_DO_TEST_BENCH_WIRING 0
#define FROM_HPS_DRIVEN_SIM_VALUE 0
#define FROM_HPS_EDGE_TYPE NONE
#define FROM_HPS_FREQ 50000000
#define FROM_HPS_HAS_IN 0
#define FROM_HPS_HAS_OUT 1
#define FROM_HPS_HAS_TRI 0
#define FROM_HPS_IRQ_TYPE NONE
#define FROM_HPS_RESET_VALUE 0

/*
 * Macros for device 'to_hps', class 'altera_avalon_pio'
 * The macros are prefixed with 'TO_HPS_'.
 * The prefix is the slave descriptor.
 */
#define TO_HPS_COMPONENT_TYPE altera_avalon_pio
#define TO_HPS_COMPONENT_NAME to_hps
#define TO_HPS_BASE 0x10
#define TO_HPS_SPAN 16
#define TO_HPS_END 0x1f
#define TO_HPS_BIT_CLEARING_EDGE_REGISTER 0
#define TO_HPS_BIT_MODIFYING_OUTPUT_REGISTER 0
#define TO_HPS_CAPTURE 0
#define TO_HPS_DATA_WIDTH 32
#define TO_HPS_DO_TEST_BENCH_WIRING 0
#define TO_HPS_DRIVEN_SIM_VALUE 0
#define TO_HPS_EDGE_TYPE NONE
#define TO_HPS_FREQ 50000000
#define TO_HPS_HAS_IN 1
#define TO_HPS_HAS_OUT 0
#define TO_HPS_HAS_TRI 0
#define TO_HPS_IRQ_TYPE NONE
#define TO_HPS_RESET_VALUE 0


#endif /* _ALTERA_HPS_0_H_ */
